version: '3'
services:
  pg11:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=pgpass@123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@amis.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - pg_network

networks:
  pg_network:

volumes:
  pgdata:
  pgadmindata:
